version: '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./storybook-static:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.imweb-202204__${PROJECT_NAME}.loadbalancer.server.port=80
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.middlewares=imfe-google-oauth

  imfe-google-oauth:
    image: thomseddon/traefik-forward-auth:latest
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} # REDACTED
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_ID} # REDACTED
      - SECRET=${OAUTH_SECRET}
      - INSECURE_COOKIE=false
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.imfe-google-oauth.forwardauth.address=http://imfe-google-oauth:4181
        - traefik.http.middlewares.imfe-google-oauth.forwardauth.authResponseHeaders=X-Forwarded-User
        - traefik.http.services.imfe-google-oauth.loadbalancer.server.port=4181

networks:
  default:
    external:
      name: proxy-main
