version: '3.7'

services:
  web:
    image: nginx
    volumes:
      - ./storybook-static:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.imweb-202204__${PROJECT_NAME}.loadbalancer.server.port=80
        - traefik.http.routers.imweb-202204__${PROJECT_NAME}.middlewares=imweb-auth@file

networks:
  default:
    external:
      name: proxy-main